/**
 * Maps SMS-BUS `project_code` (lowercase) to Simple Icons slug for cdn.simpleicons.org
 * @see https://simpleicons.org/
 */
export const PROJECT_CODE_TO_SIMPLE_ICON: Record<string, string> = {
  wa: "whatsapp",
  wp: "whatsapp",
  tg: "telegram",
  fb: "facebook",
  ig: "instagram",
  go: "google",
  gg: "google",
  ds: "discord",
  tw: "x",
  tt: "tiktok",
  tk: "tiktok",
  nf: "netflix",
  am: "amazon",
  pp: "paypal",
  ap: "apple",
  ms: "microsoft",
  li: "linkedin",
  ub: "uber",
  sc: "snapchat",
  nv: "nvidia",
  ai: "openai",
  ot: "openai",
  op: "openai",
  bi: "binance",
  by: "bybit",
  ok: "okx",
  st: "steam",
  vb: "viber",
  vk: "vk",
  im: "imo",
  ln: "line",
  ym: "yahoo",
  eb: "ebay",
  hm: "hinge",
  tn: "tinder",
  rd: "reddit",
  zm: "zoom",
  sl: "slack",
  sp: "spotify",
  dc: "disneyplus",
  ad: "adobe",
  sk: "skype",
  zl: "zalo",
  tm: "temu",
  sh: "shopee",
  lz: "lazada",
  oz: "ozon",
  ya: "yandex",
  ma: "mailru",
  gm: "gmail",
  hw: "huawei",
  mi: "xiaomi",
  sm: "samsung",
  nt: "nintendo",
  ps: "playstation",
  ep: "epicgames",
  ea: "ea",
  bl: "blizzard",
  ri: "riotgames",
  tf: "twitch",
  gh: "github",
  gl: "gitlab",
  bd: "baidu",
  jd: "jdcom",
  tb: "taobao",
  al: "alibaba",
  wm: "walmart",
  cv: "anthropic",
  ch: "openai",
  pi: "pinterest",
  wi: "wise",
  fi: "figma",
  ve: "vercel",
  dr: "discord",
  cp: "canva",
  po: "microsoft",
  nf2: "netflix",
  ze: "zoho",
  gr: "grindr",
  ba: "badoo",
  bo: "bolt",
  ca: "canva",
  ci: "claude",
  di: "discord",
  fu: "fiverr",
  ho: "hopi",
  ka: "kakaotalk",
  ke: "kwai",
  le: "leboncoin",
  ly: "lyft",
  na: "naver",
  ne: "netflix",
  ni: "nike",
  no: "notion",
  ol: "olx",
  ou: "offerup",
  pa: "paysafe",
  pl: "playstation",
  pr: "proton",
  re: "revolut",
  ro: "roblox",
  sb: "sberbank",
  si: "signal",
  sn: "snapchat",
  so: "sony",
  te: "telegram",
  tr: "tinder",
  vi: "viber",
  vo: "vodafone",
  we: "wechat",
  wo: "wolt",
  xi: "xiaomi",
  ye: "yemeksepeti",
  yo: "youtube",
};

/** Match service title to a known Simple Icons slug when code is ambiguous */
const TITLE_SLUG_HINTS: [RegExp, string][] = [
  [/whatsapp/i, "whatsapp"],
  [/telegram/i, "telegram"],
  [/tiktok|douyin/i, "tiktok"],
  [/google|gmail|youtube/i, "google"],
  [/instagram|threads/i, "instagram"],
  [/facebook/i, "facebook"],
  [/discord/i, "discord"],
  [/twitter/i, "x"],
  [/netflix/i, "netflix"],
  [/amazon/i, "amazon"],
  [/paypal/i, "paypal"],
  [/apple/i, "apple"],
  [/microsoft|azure/i, "microsoft"],
  [/linkedin/i, "linkedin"],
  [/uber/i, "uber"],
  [/snapchat/i, "snapchat"],
  [/openai|chatgpt/i, "openai"],
  [/claude|anthropic/i, "anthropic"],
  [/binance/i, "binance"],
  [/bybit/i, "bybit"],
  [/okx/i, "okx"],
  [/steam/i, "steam"],
  [/viber/i, "viber"],
  [/vkontakte|в контакте/i, "vk"],
  [/line(?!\s)/i, "line"],
  [/yahoo/i, "yahoo"],
  [/ebay/i, "ebay"],
  [/hinge/i, "hinge"],
  [/tinder/i, "tinder"],
  [/reddit/i, "reddit"],
  [/zoom/i, "zoom"],
  [/slack/i, "slack"],
  [/spotify/i, "spotify"],
  [/disney/i, "disneyplus"],
  [/adobe/i, "adobe"],
  [/skype/i, "skype"],
  [/zalo/i, "zalo"],
  [/temu/i, "temu"],
  [/shopee/i, "shopee"],
  [/lazada/i, "lazada"],
  [/ozon/i, "ozon"],
  [/yandex/i, "yandex"],
  [/gmail/i, "gmail"],
  [/huawei/i, "huawei"],
  [/xiaomi/i, "xiaomi"],
  [/samsung/i, "samsung"],
  [/nintendo/i, "nintendo"],
  [/playstation|pubg/i, "playstation"],
  [/epic/i, "epicgames"],
  [/blizzard|battle/i, "blizzard"],
  [/riot/i, "riotgames"],
  [/twitch/i, "twitch"],
  [/github/i, "github"],
  [/gitlab/i, "gitlab"],
  [/baidu/i, "baidu"],
  [/京东|jd/i, "jdcom"],
  [/taobao/i, "taobao"],
  [/alibaba/i, "alibaba"],
  [/walmart/i, "walmart"],
  [/pinterest/i, "pinterest"],
  [/wise/i, "wise"],
  [/figma/i, "figma"],
  [/vercel/i, "vercel"],
  [/notion/i, "notion"],
  [/canva/i, "canva"],
  [/roblox/i, "roblox"],
  [/signal/i, "signal"],
  [/wechat|weibo/i, "wechat"],
  [/grindr/i, "grindr"],
  [/badoo/i, "badoo"],
  [/bolt\b/i, "bolt"],
  [/fiverr/i, "fiverr"],
  [/kakao/i, "kakaotalk"],
  [/kwai/i, "kwai"],
  [/leboncoin/i, "leboncoin"],
  [/lyft/i, "lyft"],
  [/naver/i, "naver"],
  [/nike/i, "nike"],
  [/olx/i, "olx"],
  [/offerup/i, "offerup"],
  [/foodpanda/i, "foodpanda"],
  [/happn/i, "happn"],
  [/venmo/i, "venmo"],
  [/coinbase/i, "coinbase"],
  [/zoho/i, "zoho"],
  [/bet365/i, "bet365"],
  [/betfair/i, "betfair"],
  [/tradingview/i, "tradingview"],
  [/nvidia/i, "nvidia"],
  [/razer/i, "razer"],
  [/ubisoft/i, "ubisoft"],
  [/carrefour/i, "carrefour"],
  [/talabat/i, "talabat"],
];

function slugifyTitle(title: string): string {
  const chunk = title.split(/[/／|]/)[0].trim();
  return chunk
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "")
    .slice(0, 32);
}

/**
 * Simple Icons CDN — returns URL or null to use initials fallback.
 */
export function getServiceIconUrl(projectCode: string, projectTitle: string): string | null {
  const code = projectCode.trim().toLowerCase();
  if (code && PROJECT_CODE_TO_SIMPLE_ICON[code]) {
    return `https://cdn.simpleicons.org/${PROJECT_CODE_TO_SIMPLE_ICON[code]}`;
  }
  for (const [re, slug] of TITLE_SLUG_HINTS) {
    if (re.test(projectTitle)) {
      return `https://cdn.simpleicons.org/${slug}`;
    }
  }
  const fromTitle = slugifyTitle(projectTitle);
  if (fromTitle.length >= 3) {
    return `https://cdn.simpleicons.org/${fromTitle}`;
  }
  return null;
}
